### ISSUE TITLE
FUNKTASTIC! FUNKtion intro night

### ISSUE THREAD

**Issue by keee99** [OpenSUTD/DiscoverSUTD-2021-microsite#126]
**Session Name**
FUNKTASTIC! FUNKtion intro night

**Abstract**
Freshies will be exposed to various aspects of FUNKtion, such as the locking and popping dance styles, freestyle, and the club culture, through a taster training session.

**Student Organisation organising this session**
FUNKtion

**Event Format**
Physical

**Session intent (what to expect)**
Participants will get a _taste_ of what training is like in our trainings.
Participants will be introduced to the locking and popping _dance styles_ that we use at FUNKtion.
Most importantly, participants will have _FUN_!!! After all, we’re (FUN)Ktion! :)
_No prerequisites_: Those with 0 dance experience welcome! (PS, 90% of our dancers are new to dance when they first join!)

**Session details**
Venue: Dance Studio 3, 4, 5, Level 2 of Indoor Sports Hall (Blk 61)
Dates: 
20 September 2021 (Mon)
23 September 2021 (Thurs) 
27 September 2021 (Mon)
30 September 2021 (Thurs)

Time: 7.30pm - 9.30pm*
Expected participants: Maximum 27 per session (10 seniors, 15 freshies and 2 instructors)

*If dance activities are NOT limited to 2 hours from COVID19 restrictions, timing is 7pm - 10pm instead

**Workshop facilitators**
Mondays: Jin Neo - our locking instructor! Instagram: @j.nry
Thursdays: Funkstyle KS - our popping instructor! Instagram: @funkstyle_ks
Club members will also assist the instructors to teach dance moves and answer questions that participants may bring up.

**Sign up link**
Signup link: https://forms.office.com/r/GDRyMpXS9G 
Telegram link: https://t.me/joinchat/1CqEeePt8Q8zMTk1 

**Logistical details / Budget Needed**
NIL

**Comment by makehahaz** [comment]
Hi @keee99 , thank you for your submission! Just to check whether the Dance studio venues have already been booked by your club?

**Comment by keee99** [comment]
The event is during our normal training time. While it hasn't been booked, we are planning to book it as part of the normal start-of-term venue bookings. However, if you can book it now to help secure the location, that'll be helpful.

**Comment by makehahaz** [comment]
Cool! Understood

**Comment by castlemas** [comment]
@keee99

Hi FUNKtion, thanks for writing the proposal !

Regarding the venue of Dance Studio 3-5, would it be alright if FUNKtion explore to use Dance Studio 1,2,9 instead of Dance Studio 3,4,5? Unfortunately, we are unable to acquire a booking for MPH for our DiscoverSUTD-2021 Supper with Seniors event due to changes in the booking requirements.

Tentatively Supper with Seniors dates & time:
16/9, 20/9, 21/9, 22/9, 23/9, 27/9, 28/9, 29/9
8:30pm - 10:00pm

We noticed a clash in our event dates of
20/9, 23/9, 27/9
7:00pm - 10:00pm

We considered using Dance Studio 1,2,9 for the other dates, however, as there are 8 Supper sessions and there is a need for tables and chairs, Housing would prefer if we use the same Dance Studio instead of the other vacant studios to prevent the staff from shifting the furnitures around.

If that is ok, **we will help with the request of booking for Dance Studio 1,2,9 for 20/9, 23/9, 27/9, 30/9, 7:00pm - 10:00pm.**
Below are the capacity details:
Dance Studio 1: 12pax
Dance Studio 2: 8pax
Dance Studio 9: 10pax
Total capacity: 30pax
_Dance Studio 1 and 2 can be combined._

**Comment by keee99** [comment]
@castlemas 
Hello, we have difficulty in doing so as we cannot split our session into different venues. We are in the midst of discussion, is it ok if we reply to you by Monday night?

**Comment by castlemas** [comment]
@keee99 

Sure, it's alright!

**Comment by keee99** [comment]
Hello, I regret to inform that DS1, 2 won't be able to accommodate the pax limit that we are looking for, which may affect our membership, and we are also planning to have showcases which require space that DS1,2 do not provide. Additionally, we cannot use DS9 as the studio is not linked and we only have 1 instructor per session. Thus, we are unable to switch the venues. Sorry for the inconvenience!! ://

**Comment by castlemas** [comment]
@keee99 

Ah, alright. I just spoke to my OSL lets compromise here! We will be using DS 3,4,5 on the dates that do not clash and DS 1,2 on the other dates.

**Comment by castlemas** [comment]
@keee99

Ah, alright. I just spoke to my OSL, lets compromise! We will be using DS 3,4,5 on the dates that do not clash and DS 1,2 on the other dates. We have a small favour to ask from FUNKtion team...

In the case where this Scenario happens:
Supper held at DS345 on 21/9, after Supper ends, we might not be able to move the chairs up to DS1,2 for our next Supper date 22/9 as the doors might be locked. The Supper team would stack the chairs aside at DS3,4,5. When the next day arrived and the doors to DS1,2 unlock, **could I trouble FUNKtion team to come earlier so that we could move the chairs and set up the Supper venue at DS1,2?**
Also, do note that as the tables might be too big to move to DS1,2, there is a chance that the tables (cohort classroom long rectangle ones) will be stacked at the corners of DS345. 

Let me know if you have any questions!

Thank you xx

**Comment by keee99** [comment]
@castlemas Sorry for the late reply! As Ignatius replied on telegram, we are willing to help and provide manpower to shift the furniture and set up the venue. Please do inform us of any further instructions that we may need to know! :)

**Comment by castlemas** [comment]
ps accidentally clicked close issue @ExtremelySunnyYK  !
